# Generated by Django 3.2.6 on 2021-11-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_courses_course_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
